# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: oc-cmd@2
  inputs:
    openshiftService: 'OpenShift Connection'
    cmd: 'oc new-app --name=dotnetapp2 ''dotnet:2.1~https://github.com/angelosleebos/s2i-dotnetcore-ex#dotnetcore-2.1'' --build-env DOTNET_STARTUP_PROJECT=app'
